#!/bin/bash

optimal_node=25
initial_node=()
initial_node+=( "`awk '/set X|set Y|set Z/' mobility_1.tcl > initial_node.txt`" )
#initial_node+=( "`awk '/set X|set Y|set Z/' mobility_1.tcl >> mobility_1_edit.tcl`" )

node_txt=initial_node.txt
for ((i=1; i<$optimal_node; i++));
do
	printf '$node_('$i') set X_ 2053.82
$node_('$i') set Y_ 2704.38
$node_('$i') set Z_ 0\n' >> optimal_$optimal_node.tcl
	
done
#echo $initial_node
#awk '{if($4="\"$node_(0)\"") print $4}' mobility_1.tcl
#initial_node=`awk `

awk '/ns_/{print}' mobility_1.tcl > movement.txt



if [[ -f movement_temp.txt ]]
then
	rm movement_temp.txt
	for ((i=0; i<$optimal_node; i++));
	do
	#awk '{sub(/node_(0)/, "node_(a)")}1' movement.txt > movement_temp.txt
	#sed -i '/X/s/node_(0)/node_('$i')/' mobility_1.tcl >> initial_node_temp.txt
	#sed  '/\[node_]/i Hello World' input
	sed 's/node_(0)/node_('$i')/' movement.txt >> movement_temp.txt

	done
else
	for ((i=0; i<$optimal_node; i++));
	do
	#awk '{sub(/node_(0)/, "node_(a)")}1' movement.txt > movement_temp.txt
	#sed -i '/X/s/node_(0)/node_('$i')/' mobility_1.tcl >> initial_node_temp.txt
	#sed  '/\[node_]/i Hello World' input
		sed 's/node_(0)/node_('$i')/' movement.txt >> movement_temp.txt

	done
fi

time=0.25
addition=50.0
if [[ -f test.txt ]]
then
	rm test.txt
	for ((i=0; i<$optimal_node; i++));
	do
		awk -v waktu=$time '/\('$i')/{print $1,$2,$3+waktu,$4,$5,$6,$7,$8}' movement_temp.txt >> test.txt
		time=$(echo "$time + $addition" | bc)
	done
else
	for ((i=0; i<$optimal_node; i++));
	do
		awk -v waktu=$time '/\('$i')/{print $1,$2,$3+waktu,$4,$5,$6,$7,$8}' movement_temp.txt >> test.txt
		time=$(echo "$time + $addition" | bc)
	done
fi




cat test.txt >> optimal_$optimal_node.tcl
