#!/bin/bash
#inisialisasi masing2 trace file

gsmamrtrace50=()
gsmamrtrace70=()


gsmamrtrace50+=( `awk '/50/' ../trace_log_gsm_amr` )
gsmamrtrace70+=( `awk '/70/' ../trace_log_gsm_amr` )

if (( ${#gsmamrtrace50[@]} )); then
	echo "isi bosque"
	if [[ -f gsmamr_pktloss_50.txt ]]
	then
		rm gsmamr_pktloss_50.txt
		for i in "${gsmamrtrace50[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=50 -f packetloss.awk ../trace/$i >> gsmamr_pktloss_50.txt
		
		done
	else
		for i in "${gsmamrtrace50[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=50 -f packetloss.awk ../trace/$i >> gsmamr_pktloss_50.txt
		done
	fi
	echo "file hasil trace node 50"
else
	echo "Tidak ada file trace dengan node 50"
fi

if (( ${#gsmamrtrace70[@]} )); then
	echo "isi bosque"
	if [[ -f gsmamr_pktloss_70.txt ]]
	then
		rm gsmamr_pktloss_70.txt
		for i in "${gsmamrtrace70[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
			#usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=70 -f packetloss.awk ../trace/$i >> gsmamr_pktloss_70.txt
		
		done
	else
		for i in "${gsmamrtrace70[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
			#usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=70 -f packetloss.awk ../trace/$i >> gsmamr_pktloss_70.txt
		done
	fi
	echo "file hasil trace node 70"
else
	echo "Tidak ada file trace dengan node 70"
fi