#!/bin/bash

rm outputs/*
rm trace/*
rm nam/*
rm R/*

#generate mobility
#./generate_mobility

./script-n
cd awk #pindah direktori
./calculate
cd .. #pindah direktori
./mos_calculate
#./home/adisaputra/NS/voip/Project-Jitter-Buffer-master/awk/calculate
