#!/bin/bash
#inisialisasi masing2 trace file

g711trace25=()
g711trace35=()
g711trace45=()
g711trace55=()
g711trace65=()
g711trace75=()
#g711trace50=()
#g711trace70=()

g711trace25+=( `awk '/-25-/' ../trace_log_g_711` )
g711trace35+=( `awk '/-35-/' ../trace_log_g_711` )
g711trace45+=( `awk '/-45-/' ../trace_log_g_711` )
g711trace55+=( `awk '/-55-/' ../trace_log_g_711` )
g711trace65+=( `awk '/-65-/' ../trace_log_g_711` )
g711trace75+=( `awk '/-75-/' ../trace_log_g_711` )
#g711trace50+=( `awk '/50/' ../trace_log_g_711` )
#g711trace70+=( `awk '/70/' ../trace_log_g_711` )

echo "*************calculate packetloss for g711 codec************"
sleep 3
if (( ${#g711trace25[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_25.txt ]]
	then
		rm g711_pktloss_25.txt
		for i in "${g711trace25[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=25 -f packetloss.awk ../trace/$i >> g711_pktloss_25.txt
		
		done
	else
		for i in "${g711trace25[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=25 -f packetloss.awk ../trace/$i >> g711_pktloss_25.txt
		done
	fi
	echo "file hasil trace node 25"
else
	echo "Tidak ada file trace dengan node 25"
fi

if (( ${#g711trace35[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_35.txt ]]
	then
		rm g711_pktloss_35.txt
		for i in "${g711trace35[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=35 -f packetloss.awk ../trace/$i >> g711_pktloss_35.txt
		
		done
	else
		for i in "${g711trace35[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=35 -f packetloss.awk ../trace/$i >> g711_pktloss_35.txt
		done
	fi
	echo "file hasil trace node 35"
else
	echo "Tidak ada file trace dengan node 35"
fi

if (( ${#g711trace45[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_45.txt ]]
	then
		rm g711_pktloss_45.txt
		for i in "${g711trace45[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=45 -f packetloss.awk ../trace/$i >> g711_pktloss_45.txt
		
		done
	else
		for i in "${g711trace45[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=45 -f packetloss.awk ../trace/$i >> g711_pktloss_45.txt
		done
	fi
	echo "file hasil trace node 45"
else
	echo "Tidak ada file trace dengan node 45"
fi

if (( ${#g711trace55[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_55.txt ]]
	then
		rm g711_pktloss_55.txt
		for i in "${g711trace55[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=55 -f packetloss.awk ../trace/$i >> g711_pktloss_55.txt
		
		done
	else
		for i in "${g711trace55[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=55 -f packetloss.awk ../trace/$i >> g711_pktloss_55.txt
		done
	fi
	echo "file hasil trace node 55"
else
	echo "Tidak ada file trace dengan node 55"
fi

if (( ${#g711trace65[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_65.txt ]]
	then
		rm g711_pktloss_65.txt
		for i in "${g711trace65[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=65 -f packetloss.awk ../trace/$i >> g711_pktloss_65.txt
		
		done
	else
		for i in "${g711trace65[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=65 -f packetloss.awk ../trace/$i >> g711_pktloss_65.txt
		done
	fi
	echo "file hasil trace node 65"
else
	echo "Tidak ada file trace dengan node 65"
fi

if (( ${#g711trace75[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_75.txt ]]
	then
		rm g711_pktloss_75.txt
		for i in "${g711trace75[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=75 -f packetloss.awk ../trace/$i >> g711_pktloss_75.txt
		
		done
	else
		for i in "${g711trace75[@]}"
		do
			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=75 -f packetloss.awk ../trace/$i >> g711_pktloss_75.txt
		done
	fi
	echo "file hasil trace node 75"
else
	echo "Tidak ada file trace dengan node 75"
fi

#if (( ${#g711trace50[@]} )); then
#	echo "isi bosque"
#	if [[ -f g711_pktloss_50.txt ]]
#	then
#		rm g711_pktloss_50.txt
#		for i in "${g711trace50[@]}"
#		do
#			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
#			awk -v node=50 -f packetloss.awk ../trace/$i >> g711_pktloss_50.txt
		
#		done
#	else
#		for i in "${g711trace50[@]}"
#		do
#			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
#			awk -v node=50 -f packetloss.awk ../trace/$i >> g711_pktloss_50.txt
#		done
#	fi
#	echo "file hasil trace node 50"
#else
#	echo "Tidak ada file trace dengan node 50"
#fi

#if (( ${#g711trace70[@]} )); then
#	echo "isi bosque"
#	if [[ -f g711_pktloss_70.txt ]]
#	then
#		rm g711_pktloss_70.txt
#		for i in "${g711trace70[@]}"
#		do
#			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
			#usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
#			awk -v node=70 -f packetloss.awk ../trace/$i >> g711_pktloss_70.txt
		
#		done
#	else
#		for i in "${g711trace70[@]}"
#		do
#			echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
			#usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
#			awk -v node=70 -f packetloss.awk ../trace/$i >> g711_pktloss_70.txt
#		done
#	fi
#	echo "file hasil trace node 70"
#else
#	echo "Tidak ada file trace dengan node 70"
#fi
