#!/bin/bash
#inisialisasi masing2 trace file

g711trace25=()
g711trace50=()
g711trace70=()

g711trace25+=( `awk '/25/' ../trace_log_g_711` )
g711trace50+=( `awk '/50/' ../trace_log_g_711` )
g711trace70+=( `awk '/70/' ../trace_log_g_711` )


if (( ${#g711trace25[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_25.txt ]]
	then
		rm g711_pktloss_25.txt
		for i in "${g711trace25[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=25 -f packetloss.awk ../trace/$i >> g711_pktloss_25.txt
		
		done
	else
		for i in "${g711trace25[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=25 -f packetloss.awk ../trace/$i >> g711_pktloss_25.txt
		done
	fi
	echo "file hasil trace node 25"
else
	echo "Tidak ada file trace dengan node 25"
fi

if (( ${#g711trace50[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_50.txt ]]
	then
		rm g711_pktloss_50.txt
		for i in "${g711trace50[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=50 -f packetloss.awk ../trace/$i >> g711_pktloss_50.txt
		
		done
	else
		for i in "${g711trace50[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
            #usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=50 -f packetloss.awk ../trace/$i >> g711_pktloss_50.txt
		done
	fi
	echo "file hasil trace node 50"
else
	echo "Tidak ada file trace dengan node 50"
fi

if (( ${#g711trace70[@]} )); then
	echo "isi bosque"
	if [[ -f g711_pktloss_70.txt ]]
	then
		rm g711_pktloss_70.txt
		for i in "${g711trace70[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
			#usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=70 -f packetloss.awk ../trace/$i >> g711_pktloss_70.txt
		
		done
	else
		for i in "${g711trace70[@]}"
		do
			#echo $i
			#hasil+=( `awk -f e2e.awk ../trace/$i` )
			#usage awk -v node=jumnode -f packetloss.awk tracefile >> hasil
			awk -v node=70 -f packetloss.awk ../trace/$i >> g711_pktloss_70.txt
		done
	fi
	echo "file hasil trace node 70"
else
	echo "Tidak ada file trace dengan node 70"
fi
