#!/bin/bash
####
#mobility & traffic generation
####
try=(1 2 3 4 5 6 7 8 9 10)
nnode=(23 33 43 53 63 73) #definisikan jumlah node
mobility=()

#ganti osm file dengan file osm yang dipakai
proj=NS/voip/Project-Jitter-Buffer-master
netfiles=osmfiles/netfiles/mau_sebudi.net.xml
poly=osmfiles/polyfiles
rout=osmfiles/roufiles
sumocfg=osmfiles/sumocfg
sumoxml=osmfiles/sumoxml
ns2config=osmfiles/ns2config
ns2mobility=osmfiles/mobility
rerouter=osmfiles/netfiles/rerouter.add.xml
type=osmfiles/netfiles/type.add.xml

#netconvert --osm-files $osm -o $netfiles/netfiles.net.xml
for k in "${try[@]}"
do
	for i in "${nnode[@]}"
	do
		echo "replikasi mobility ke $k node $i"
		#polyconvert proses
		echo "***********Generate Mobility for $i node***************"
		echo "polyconvert proccess"
		polyconvert --osm-files osmfiles/mau_sebudi.osm --net-file $netfiles --type-file $SUMO_HOME/data/typemap/osmPolyconvert.typ.xml -o $poly/${i}_${k}.poly.xml
		#randomTrips.py proses
		echo "randomTrips proccess"
		#python $SUMO_HOME/tools/randomTrips.py --trip-attributes="type=\"myType\"" -n $netfiles -a $rerouter -a $type -r $rout/$i.rou.xml -e $i -l #ini akan generate n node hingga $i second, 1 node per 1 second, jadi jika ini $i=50, maka 10 node dalam 10 detik 
		#dalam 50 detik
		x=0
		x=`awk -v var1=1 -v var2=$i 'BEGIN { print  ( var1 / var2 ) }'`
		echo $x
		y=0
		y=`awk -v var1=$x -v var2=1 'BEGIN { print ( var2 / var1 ) }'`
		echo $y
		round=0
		round=`awk -v var1=$y 'BEGIN { printf("%.0f", var1) }'`
		echo $round
		
		#python $SUMO_HOME/tools/randomTrips.py -n $netfiles -r $rout/$i.rou.xml -e 1 -p 0.02 -l #akan membuat 1/0.02 node dalam 1 detik. 
		python $SUMO_HOME/tools/randomTrips.py --trip-attributes="type=\"myType\"" -n $netfiles -a $type -r $rout/${i}_${k}.rou.xml -e 1 -p $x -l #akan membuat 1/$x node dalam 1 detik pada file route.
		#echo "membuat $round node per 1 detik"
		sleep 2
		

		echo "building $i sumo.cfg configuration"
		printf "<configuration>
				<input>
					<net-file value='"$HOME/$proj/$netfiles"'/>
				<route-files value='"$HOME/$proj/$rout/${i}_${k}.rou.xml"'/>
				<additional-files value='"$HOME/$proj/$poly/${i}_${k}.poly.xml"'/>
				</input>
			<time>
				<begin value='"0"'/>
				<end value='"120"'/>
				<step-length value='"0.1"'/>
			</time>
			 </configuration>" > $sumocfg/${i}_${k}.sumo.cfg

		echo "sumo.xml files creating ....."
		sumo -c $HOME/$proj/$sumocfg/${i}_${k}.sumo.cfg --fcd-output $sumoxml/${i}_${k}.sumo.xml

		echo "mobility creating with traceExporter"
		python $SUMO_HOME/tools/traceExporter.py --fcd-input $sumoxml/${i}_${k}.sumo.xml --ns2config-output $ns2config/config_${i}_${k}.tcl
		python $SUMO_HOME/tools/traceExporter.py --fcd-input $sumoxml/${i}_${k}.sumo.xml --ns2mobility-output $ns2mobility/mobility_${i}_${k}.tcl

			#append array mobility
			mobility+=( $ns2mobility/mobility_$i_$k.tcl )
	done
done

